// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package example

import (
	"context"

	"github.com/evenyosua18/go-project-template/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIExampleUsecase creates a new instance of MockIExampleUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExampleUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExampleUsecase {
	mock := &MockIExampleUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIExampleUsecase is an autogenerated mock type for the IExampleUsecase type
type MockIExampleUsecase struct {
	mock.Mock
}

type MockIExampleUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIExampleUsecase) EXPECT() *MockIExampleUsecase_Expecter {
	return &MockIExampleUsecase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIExampleUsecase
func (_mock *MockIExampleUsecase) Get(ctx context.Context, request entity.GetExampleRequest) (entity.GetExampleResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.GetExampleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.GetExampleRequest) (entity.GetExampleResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.GetExampleRequest) entity.GetExampleResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.GetExampleResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.GetExampleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExampleUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIExampleUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.GetExampleRequest
func (_e *MockIExampleUsecase_Expecter) Get(ctx interface{}, request interface{}) *MockIExampleUsecase_Get_Call {
	return &MockIExampleUsecase_Get_Call{Call: _e.mock.On("Get", ctx, request)}
}

func (_c *MockIExampleUsecase_Get_Call) Run(run func(ctx context.Context, request entity.GetExampleRequest)) *MockIExampleUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.GetExampleRequest
		if args[1] != nil {
			arg1 = args[1].(entity.GetExampleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExampleUsecase_Get_Call) Return(getExampleResponse entity.GetExampleResponse, err error) *MockIExampleUsecase_Get_Call {
	_c.Call.Return(getExampleResponse, err)
	return _c
}

func (_c *MockIExampleUsecase_Get_Call) RunAndReturn(run func(ctx context.Context, request entity.GetExampleRequest) (entity.GetExampleResponse, error)) *MockIExampleUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}
