// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	example2 "github.com/evenyosua18/go-project-template/app/repository/db/example"
	"github.com/evenyosua18/go-project-template/app/server/rest/public/v1/api/example"
	example3 "github.com/evenyosua18/go-project-template/app/usecase/example"
)

// Injectors from example.go:

func InitExample() *example.ApiExample {
	iExampleRepository := example2.NewExampleRepository()
	iExampleUsecase := example3.NewExampleUsecase(iExampleRepository)
	apiExample := example.NewExampleApi(iExampleUsecase)
	return apiExample
}
