// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package example

import (
	"context"

	"github.com/evenyosua18/go-project-template/app/repository/db/example"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIExampleRepository creates a new instance of MockIExampleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExampleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExampleRepository {
	mock := &MockIExampleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIExampleRepository is an autogenerated mock type for the IExampleRepository type
type MockIExampleRepository struct {
	mock.Mock
}

type MockIExampleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIExampleRepository) EXPECT() *MockIExampleRepository_Expecter {
	return &MockIExampleRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIExampleRepository
func (_mock *MockIExampleRepository) Get(ctx context.Context, filter example.FilterExample) (example.Example, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 example.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, example.FilterExample) (example.Example, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, example.FilterExample) example.Example); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(example.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, example.FilterExample) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExampleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIExampleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - filter example.FilterExample
func (_e *MockIExampleRepository_Expecter) Get(ctx interface{}, filter interface{}) *MockIExampleRepository_Get_Call {
	return &MockIExampleRepository_Get_Call{Call: _e.mock.On("Get", ctx, filter)}
}

func (_c *MockIExampleRepository_Get_Call) Run(run func(ctx context.Context, filter example.FilterExample)) *MockIExampleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 example.FilterExample
		if args[1] != nil {
			arg1 = args[1].(example.FilterExample)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExampleRepository_Get_Call) Return(example1 example.Example, err error) *MockIExampleRepository_Get_Call {
	_c.Call.Return(example1, err)
	return _c
}

func (_c *MockIExampleRepository_Get_Call) RunAndReturn(run func(ctx context.Context, filter example.FilterExample) (example.Example, error)) *MockIExampleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
